spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SplitLedger
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


jwt:
  secret: mvmfX43DpDuBlWSdw6j1jYhAIohUP8Jp
  access-token-expiration: 36000000
  refresh-token-expiration: 604800000
